name: "Delete PR review comments"
description: "Delete PR review comments by any conditions"
author: "aki77"
branding:
  icon: trash-2
  color: red
inputs:
  token:
    required: true
    description: "Github token"
  bodyContains:
    required: false
    description: "Delete only comments containing strings."
  noReply:
    required: false
    description: "Delete only comments with no replies."
    default: "false"
runs:
  using: "node20"
  main: "dist/index.js"
